/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class Doctor_Details extends javax.swing.JFrame {

    /**
     * Creates new form AddDoctor
     */
    public Doctor_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel1.setText("DOCTOR - DETAILS ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 80, 370, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel2.setText("Doctor  ID : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 180, 170, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel3.setText("First Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 240, 170, 30);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel4.setText("Second  Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(600, 240, 180, 30);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(230, 180, 240, 30);

        jTextField2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(230, 240, 240, 30);

        jTextField3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(790, 240, 240, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel5.setText("Age :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 300, 170, 30);

        jTextField4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(230, 300, 240, 30);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel6.setText("Blood Group :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(600, 300, 190, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A +", "B+", "AB +", "O+", "AB -", "O-", "A-", "B-" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(790, 300, 240, 30);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 360, 170, 30);

        jComboBox2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(230, 360, 240, 30);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel8.setText("Departments :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(600, 360, 190, 30);

        jComboBox3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allergists/Immunologists", "Anesthesiologists", "Cardiologists", "Colon and Rectal Surgeons", "Critical Care Medicine Specialists", "Dermatologists", "Endocrinologists", "Emergency Medicine Specialists", "Family Physicians", "Gastroenterologists", "Geriatric Medicine Specialists", "Neurologists", "Obstetricians and Gynecologists", "General Surgeons", "Sports Medicine Specialists", "Sleep Medicine Specialists", "Rheumatologists", "Radiologists", "Pulmonologists", "PediatriciansPhysiatristsPlastic Surgeons", "Psychiatrists", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " " }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(790, 360, 240, 30);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel9.setText("Address :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 420, 170, 30);

        jTextField5.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(230, 420, 350, 30);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel10.setText("Phone  Number :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 420, 190, 30);

        jTextField6.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(790, 420, 240, 30);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel11.setText("Marital  Status :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 480, 230, 30);

        jComboBox4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unmarried", "Married" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(230, 480, 240, 30);

        jLabel12.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel12.setText("Joining  Date :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 540, 190, 30);

        jTextField7.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(790, 480, 240, 30);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel13.setText("Leaving  Date :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(600, 540, 210, 30);

        jTextField8.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(230, 540, 240, 30);

        jLabel14.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel14.setText("Visiting  Time :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 600, 190, 30);

        jTextField9.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField9);
        jTextField9.setBounds(790, 540, 240, 30);

        jLabel15.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel15.setText("City / State :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(600, 480, 180, 30);

        jLabel16.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel16.setText("UserName :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 660, 190, 30);

        jTextField11.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField11);
        jTextField11.setBounds(230, 660, 240, 30);

        jLabel17.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel17.setText("Password :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(600, 660, 170, 30);

        jTextField12.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField12);
        jTextField12.setBounds(790, 660, 240, 30);

        jButton1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/add.png"))); // NOI18N
        jButton1.setText("ADD  DOCTOR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 270, 40);

        jButton3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/delete.png"))); // NOI18N
        jButton3.setText("DELETE  DOCTOR ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(540, 0, 280, 40);

        jButton4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/update.png"))); // NOI18N
        jButton4.setText("UPDATE  DOCTOR ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(270, 0, 280, 40);

        jButton5.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/view.png"))); // NOI18N
        jButton5.setText("VIEW DOCTOR ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(820, 0, 260, 40);

        jButton6.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/search.png"))); // NOI18N
        jButton6.setText("SEARCH  DOCTOR ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(580, 170, 300, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 730, 1480, 160);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/left.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(0, 40, 60, 50);

        jLabel19.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel19.setText("Visiting Days :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(600, 600, 220, 30);

        jComboBox5.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday - Tuesday", "Monday - Wednesday", "Tuesday - Wednesday", "Tuesday - Thursday", "Wednesday - Thursday", "Wednesday - Friday", "Thursday - Saturday", "Thursday - Friday" }));
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(790, 600, 240, 30);

        jComboBox6.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM", "09:00 PM", "10:00 PM" }));
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(230, 600, 240, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/pan.jpg"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(0, 0, 1510, 900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1530, 949));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        String s4=jTextField4.getText();
        String s5=(String) jComboBox1.getSelectedItem();
        String s6=(String) jComboBox2.getSelectedItem();
        String s7=(String) jComboBox3.getSelectedItem();
        String s8=jTextField5.getText();
        String s9=jTextField6.getText();
        String s10=(String) jComboBox4.getSelectedItem();
        String s11=jTextField7.getText();
        String s12=jTextField8.getText();
        String s13=jTextField9.getText();
        String s14=(String) jComboBox6.getSelectedItem();
        String s15=(String) jComboBox5.getSelectedItem();
        String s16=jTextField11.getText();
        String s17=jTextField12.getText();
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("UPDATE doctor_details SET `Doc_Id`='"+s1+"',`Dname`='"+s2+"',`Lname`='"+s3+"',`Age`='"+s4+"',`Bloog_Grp`='"+s5+"',`Gender`='"+s6+"',`Department`='"+s7+"',`Address`='"+s8+"',`Phone`='"+s9+"',`Marital`='"+s10+"',`City_State`='"+s11+"',`Joining`='"+s12+"',`Leaving`='"+s13+"',`Visiting_Time`='"+s14+"',`Visiting_Days`='"+s15+"',`Uname`='"+s16+"',`Password`='"+s17+"' WHERE `Doc_Id`='"+s1+"'");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Updated Successfully !!!","Updated",1);
            }
            
            else
            {
               JOptionPane.showMessageDialog(this,"Not Updated!!!","",2); 
            }
            
        } catch (SQLException e) {
            System.out.println(e);
        }
        doctortable(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        String s4=jTextField4.getText();
        String s5=(String) jComboBox1.getSelectedItem();
        String s6=(String) jComboBox2.getSelectedItem();
        String s7=(String) jComboBox3.getSelectedItem();
        String s8=jTextField5.getText();
        String s9=jTextField6.getText();
        String s10=(String) jComboBox4.getSelectedItem();
        String s11=jTextField7.getText();
        String s12=jTextField8.getText();
        String s13=jTextField9.getText();
        String s14=(String) jComboBox6.getSelectedItem();
        String s15=(String) jComboBox5.getSelectedItem();
        String s16=jTextField11.getText();
        String s17=jTextField12.getText();
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("INSERT INTO doctor_details VALUES('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"','"+s11+"','"+s12+"','"+s13+"','"+s14+"','"+s15+"','"+s16+"','"+s17+"')");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Added and Saved Successfully !!!","Added",1);
            }
            
            else
            {
               JOptionPane.showMessageDialog(this,"Not Added and Not Saved!!!","",2); 
            }
            con.close();
            
            jTextField1.setText(" ");
            jTextField2.setText(" ");
            jTextField3.setText(" ");
            jTextField4.setText(" ");
            jComboBox1.setSelectedItem(" ");
            jComboBox2.setSelectedItem(" ");
            jComboBox3.setSelectedItem(" ");
            jTextField5.setText(" ");
            jTextField6.setText(" ");
            jComboBox4.setSelectedItem(" ");
            jTextField7.setText(" ");
            jTextField8.setText(" ");
            jTextField9.setText(" ");
            jComboBox6.setSelectedItem(" ");
            jComboBox5.setSelectedItem(" ");
            jTextField11.setText(" ");
            jTextField12.setText(" ");
            
            
        } catch (SQLException e) {
            System.out.println(e);
        } 
       doctortable(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        String s4=jTextField4.getText();
        String s5=(String) jComboBox1.getSelectedItem();
        String s6=(String) jComboBox2.getSelectedItem();
        String s7=(String) jComboBox3.getSelectedItem();
        String s8=jTextField5.getText();
        String s9=jTextField6.getText();
        String s10=(String) jComboBox4.getSelectedItem();
        String s11=jTextField7.getText();
        String s12=jTextField8.getText();
        String s13=jTextField9.getText();
        String s14=(String) jComboBox6.getSelectedItem();
        String s15=(String) jComboBox5.getSelectedItem();
        String s16=jTextField11.getText();
        String s17=jTextField12.getText();
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("DELETE FROM doctor_details WHERE Doc_Id='"+s1+"'");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Deleted Successfully !!!","Added",1);
            }
            
            else
            {
               JOptionPane.showMessageDialog(this,"Not Deleted!!!","",2); 
            }
            
        } catch (SQLException e) {
            System.out.println(e);
        } 
        doctortable(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        String s4=jTextField4.getText();
        String s5=(String) jComboBox1.getSelectedItem();
        String s6=(String) jComboBox2.getSelectedItem();
        String s7=(String) jComboBox3.getSelectedItem();
        String s8=jTextField5.getText();
        String s9=jTextField6.getText();
        String s10=(String) jComboBox4.getSelectedItem();
        String s11=jTextField7.getText();
        String s12=jTextField8.getText();
        String s13=jTextField9.getText();
        String s14=(String) jComboBox6.getSelectedItem();
        String s15=(String) jComboBox5.getSelectedItem();
        String s16=jTextField11.getText();
        String s17=jTextField12.getText();
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("SELECT * FROM doctor_details VALUES('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"','"+s11+"','"+s12+"','"+s13+"','"+s14+"','"+s15+"','"+s16+"','"+s17+"')WHERE 1");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Viewed Successfully !!!","Added",1);
            }
            
            else
            {
               JOptionPane.showMessageDialog(this,"Not Viewed!!!","",2); 
            }
            
        } catch (SQLException e) {
            System.out.println(e);
        } 
        doctortable(); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AdminPanel ap=new AdminPanel();
        this.dispose();
        ap.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String s1=jTextField1.getText();
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM doctor_details WHERE Doc_Id='"+s1+"'");
            while(rs.next()){

            jTextField2.setText(rs.getString(2));
            jTextField3.setText(rs.getString(3));
            jTextField4.setText(rs.getString(4));
            jComboBox1.setSelectedItem(rs.getString(5));
            jComboBox2.setSelectedItem(rs.getString(6));
            jComboBox3.setSelectedItem(rs.getString(7));
            jTextField5.setText(rs.getString(8));
            jTextField6.setText(rs.getString(9));
            jComboBox4.setSelectedItem(rs.getString(10));
            jTextField7.setText(rs.getString(11));
            jTextField8.setText(rs.getString(12));
            jTextField9.setText(rs.getString(13));
            jComboBox6.setSelectedItem(rs.getString(14));
            jComboBox5.setSelectedItem(rs.getString(15));
            jTextField11.setText(rs.getString(16));
            jTextField12.setText(rs.getString(17));
                
                
                DefaultTableModel model;
                model=(DefaultTableModel)jTable1.getModel();
                TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
                jTable1.setRowSorter(tr);
                tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));
                
            
            }
        }
        catch (SQLException e) {
            System.out.println(e);
        } 
        doctortable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    public void doctortable()
    {
        try{
             Font f=new Font("Consolas",Font.BOLD,12);
             JTableHeader header=jTable1.getTableHeader();
             header.setFont(f);
             DriverManager.registerDriver(new com.mysql.jdbc.Driver());
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
             Statement st=con.createStatement();
             ResultSet rs=st.executeQuery("SELECT * FROM doctor_details");
             while(jTable1.getRowCount()>0)
             {
                 ((DefaultTableModel) jTable1.getModel()).removeRow(0);
             }
             int column=rs.getMetaData().getColumnCount();
             while(rs.next())
             {
                Object[] row=new Object[column];
                for(int i=1;i<=column;i++)
                {
                    row[i-1]=rs.getObject(i);
                }
               ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow()-1, row);
               
             }
             rs.close();
             con.close();
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"error!!!"+e);
             }
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
