/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author HP
 */
public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharm_Login
     */
    public Pharmacy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel1.setText("MEDICINE DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 20, 250, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(900, 90, 110, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel3.setText("Type :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(900, 140, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel4.setText("Company :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(900, 190, 100, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel5.setText("Ref._No. :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(900, 240, 81, 30);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel6.setText("Dosage :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(900, 290, 90, 30);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel7.setText("Side Effects :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(900, 340, 116, 30);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel8.setText("Manufac. Date :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(900, 390, 160, 30);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel9.setText("Expiry Date :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(900, 440, 140, 30);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel10.setText("Storage :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(900, 490, 110, 30);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel11.setText("Price :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(900, 540, 80, 30);

        jLabel12.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel12.setText("Availability :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(900, 590, 150, 30);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(1080, 90, 320, 30);

        jTextField2.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(1080, 190, 320, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablets", "Capsules", "Syrup", "Powder", "Ointments" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(1080, 140, 320, 30);

        jTextField3.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(1080, 240, 320, 30);

        jTextField4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(1080, 290, 320, 30);

        jTextField5.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(1080, 340, 320, 30);

        jTextField6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(1080, 390, 320, 30);

        jTextField7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(1080, 440, 320, 30);

        jTextField8.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(1080, 490, 320, 30);

        jTextField9.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField9);
        jTextField9.setBounds(1080, 540, 320, 30);

        jTextField10.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jPanel1.add(jTextField10);
        jTextField10.setBounds(1080, 590, 320, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/left.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(0, 0, 60, 50);

        jButton1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/add.png"))); // NOI18N
        jButton1.setText("ADD MEDICINE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(690, 710, 240, 40);

        jButton2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/delete.png"))); // NOI18N
        jButton2.setText("REMOVE MEDICINE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(930, 710, 270, 40);

        jButton3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/update.png"))); // NOI18N
        jButton3.setText("UPDATE MEDICINE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1200, 710, 270, 40);

        jButton4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton4.setText("NEXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1370, 750, 100, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/meds.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1470, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1490, 837));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Index i=new Index();
        this.dispose();
        i.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s1=jTextField1.getText();
        String s2=(String) jComboBox1.getSelectedItem();
        String s3=jTextField2.getText();
        String s4=jTextField3.getText();
        String s5=jTextField4.getText();
        String s6=jTextField5.getText();
        String s7=jTextField6.getText();
        String s8=jTextField7.getText();
        String s9=jTextField8.getText();
        String s10=jTextField9.getText();
        String s11=jTextField10.getText();

        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("INSERT INTO `pharmacy` VALUES('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"','"+s11+"')");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Added and Saved Successfully !!!","Added",1);
            }

            else
            {
                JOptionPane.showMessageDialog(this,"Not Added and Not Saved!!!","",2);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s1=jTextField1.getText();
        String s2=(String) jComboBox1.getSelectedItem();
        String s3=jTextField2.getText();
        String s4=jTextField3.getText();
        String s5=jTextField4.getText();
        String s6=jTextField5.getText();
        String s7=jTextField6.getText();
        String s8=jTextField7.getText();
        String s9=jTextField8.getText();
        String s10=jTextField9.getText();
        String s11=jTextField10.getText();

        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("DELETE FROM `pharmacy' WHERE `Name`='"+s1+"'");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Deleted Successfully !!!","Added",1);
            }

            else
            {
                JOptionPane.showMessageDialog(this,"Not Deleted!!!","",2);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String s1=jTextField1.getText();
        String s2=(String) jComboBox1.getSelectedItem();
        String s3=jTextField2.getText();
        String s4=jTextField3.getText();
        String s5=jTextField4.getText();
        String s6=jTextField5.getText();
        String s7=jTextField6.getText();
        String s8=jTextField7.getText();
        String s9=jTextField8.getText();
        String s10=jTextField9.getText();
        String s11=jTextField10.getText();

        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("UPDATE `pharmacy` SET `Name`='"+s1+"',`Type`='"+s2+"',`Company`='"+s3+"',`Ref_No`='"+s4+"',`Dosage`='"+s5+"',`SideEffects`='"+s6+"',`MFD`='"+s7+"',`ExpDate`='"+s8+"',`Storage`='"+s9+"',`Price`='"+s10+"',`Availability`='"+s11+"' WHERE `Name`='"+s1+"'");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Updated Successfully !!!","Updated",1);
            }

            else
            {
                JOptionPane.showMessageDialog(this,"Not Updated!!!","",2);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Pharmacy2 pp=new Pharmacy2();
        this.dispose();
        pp.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
