/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class Staffs extends javax.swing.JFrame {

    /**
     * Creates new form Staffs
     */
    public Staffs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel2.setText("OTHER  STAFFS   DETAILS ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 70, 490, 40);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel3.setText("STAFF  ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 220, 160, 40);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(230, 220, 270, 40);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel4.setText("First  Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 300, 170, 30);

        jTextField2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(230, 300, 260, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel5.setText("Second  Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 360, 180, 30);

        jTextField3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(230, 360, 260, 30);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel6.setText("Age :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 420, 140, 30);

        jTextField4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(230, 420, 260, 30);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 480, 180, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(230, 480, 260, 30);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel8.setText("Address :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 540, 140, 30);

        jTextField5.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(230, 540, 780, 30);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel9.setText("City / State :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(580, 300, 160, 30);

        jTextField6.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(750, 300, 260, 30);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel10.setText("Phone  Number :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(580, 360, 160, 30);

        jTextField7.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(760, 360, 250, 30);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel11.setText("Staff  Type :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(580, 420, 170, 30);

        jComboBox2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(760, 420, 250, 30);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel13.setText("Joining Date :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(580, 480, 180, 30);

        jTextField8.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(760, 480, 250, 30);

        jLabel12.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel12.setText("Leaving Date :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1080, 480, 160, 30);

        jTextField9.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jPanel1.add(jTextField9);
        jTextField9.setBounds(1240, 480, 260, 30);

        jButton1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/search.png"))); // NOI18N
        jButton1.setText("SEARCH  STAFFS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 220, 280, 40);

        jButton2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/add.png"))); // NOI18N
        jButton2.setText("ADD STAFFS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 230, 40);

        jButton3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/update.png"))); // NOI18N
        jButton3.setText("UPDATE STAFFS ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(230, 0, 250, 40);

        jButton4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/delete.png"))); // NOI18N
        jButton4.setText("DELETE STAFFS ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(480, 0, 243, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/left.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(0, 40, 50, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Staff_Id", "Fname", "Lname", "Age", "Gender", "Address", "City/State", "Phone", "Type", "Joining", "Leaving"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 640, 1520, 160);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/pan.jpg"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 1550, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1568, 855));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AdminPanel ap=new AdminPanel();
        this.dispose();
        ap.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        String s4=jTextField4.getText();
        String s5=(String) jComboBox1.getSelectedItem();
        String s6=jTextField5.getText();
        String s7=jTextField6.getText();
        String s8=jTextField7.getText();
        String s9=jTextField8.getText();
        String s10=(String) jComboBox2.getSelectedItem();
        String s11=jTextField9.getText();
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("INSERT INTO Staffs VALUES('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"','"+s11+"')");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Added and Saved Successfully !!!","Added",1);
            }
            
            else
            {
               JOptionPane.showMessageDialog(this,"Not Added and Not Saved!!!","",2); 
            }
            
        } catch (SQLException e) {
            System.out.println(e);
        } 
        stafftable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        String s4=jTextField4.getText();
        String s5=(String) jComboBox1.getSelectedItem();
        String s6=jTextField5.getText();
        String s7=jTextField6.getText();
        String s8=jTextField7.getText();
        String s9=jTextField8.getText();
        String s10=(String) jComboBox2.getSelectedItem();
        String s11=jTextField9.getText();
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("UPDATE `staffs` SET `Staff_Id`='"+s1+"',`Fname`='"+s2+"',`Lname`='"+s3+"',`Age`='"+s4+"',`Gender`='"+s5+"',`Address`='"+s6+"',`City_State`='"+s7+"',`Phone`='"+s8+"',`Joining`='"+s9+"',`Staff_Type`='"+s10+"',`Leaving`='"+s11+"' WHERE `Staff_Id`='"+s1+"'");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Updated Successfully !!!","updated",1);
            }
            
            else
            {
               JOptionPane.showMessageDialog(this,"Not Updated !!!","",2); 
            }
            
        } catch (SQLException e) {
            System.out.println(e);
        } 
       stafftable(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        String s4=jTextField4.getText();
        String s5=(String) jComboBox1.getSelectedItem();
        String s6=jTextField5.getText();
        String s7=jTextField6.getText();
        String s8=jTextField7.getText();
        String s9=jTextField8.getText();
        String s10=(String) jComboBox2.getSelectedItem();
        String s11=jTextField9.getText();
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            int a=st.executeUpdate("DELETE FROM staffs WHERE `Staff_Id`='"+s1+"'");
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Deleted Successfully !!!","Deleted",1);
            }
            
            else
            {
               JOptionPane.showMessageDialog(this,"Not Deleted !!!","",2); 
            }
            
        } catch (SQLException e) {
            System.out.println(e);
        } 
        stafftable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String s1=jTextField1.getText();
     String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        String s4=jTextField4.getText();
        String s5=(String) jComboBox1.getSelectedItem();
        String s6=jTextField5.getText();
        String s7=jTextField6.getText();
        String s8=jTextField7.getText();
        String s9=jTextField8.getText();
        String s10=(String) jComboBox2.getSelectedItem();
        String s11=jTextField9.getText();
        
        
        try
        {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM staffs WHERE `Staff_Id`='"+s1+"'");
            while(rs.next()){
               
                 jTextField2.setText(rs.getString(2));
                  jTextField2.setText(rs.getString(3));
                  jTextField4.setText(rs.getString(4));
                  jComboBox1.setSelectedItem(rs.getString(5));
                jTextField5.setText(rs.getString(6));
                jTextField6.setText(rs.getString(7));
                jTextField7.setText(rs.getString(8));
                jTextField8.setText(rs.getString(9));
                jComboBox2.setSelectedItem(rs.getString(10));
                jTextField9.setText(rs.getString(11));
        
                  
                DefaultTableModel model;
                model=(DefaultTableModel)jTable1.getModel();
                TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
                jTable1.setRowSorter(tr);
                tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));
            }
        }
        catch(SQLException e){
            System.out.println(e); 
        }
        stafftable();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void stafftable()
    {
        try{
             Font f=new Font("Consolas",Font.BOLD,12);
             JTableHeader header=jTable1.getTableHeader();
             header.setFont(f);
             DriverManager.registerDriver(new com.mysql.jdbc.Driver());
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?user=root&password=");
             Statement st=con.createStatement();
             ResultSet rs=st.executeQuery("SELECT * FROM staffs");
             while(jTable1.getRowCount()>0)
             {
                 ((DefaultTableModel) jTable1.getModel()).removeRow(0);
             }
             int column=rs.getMetaData().getColumnCount();
             while(rs.next())
             {
                Object[] row=new Object[column];
                for(int i=1;i<=column;i++)
                {
                    row[i-1]=rs.getObject(i);
                }
               ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow()-1, row);
               
             }
             rs.close();
             con.close();
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"error!!!"+e);
             }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staffs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
